version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00" # UTC
    labels:
      - "domain: deps"
      - "no-changelog"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    groups:
      prost:
        patterns:
        - "prost"
        - "prost-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "domain: ci"
      - "no-changelog"
    commit-message:
      prefix: "chore(ci)"
