name: Feature
type: 'Feature'
description: 🚀 Suggest a new feature.
labels:
  - 'type: feature'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a feature request! 🚀

        For general questions about VRL usage, please see https://github.com/vectordotdev/vrl/discussions

  - type: textarea
    attributes:
      label: A note for the community
      value: |
        <!-- Please keep this note for the community -->
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment.
        <!-- Thank you for keeping this note for the community -->

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: |
        In order to properly evaluate a feature request, it is necessary to
        understand the use-cases for it.

        Please describe below the _end goal_ you are trying to achieve that has
        led you to request this feature.

        Please keep this section focused on the problem and not on the suggested
        solution. We'll get to that in a moment, below!


  - type: textarea
    id: attempted-solutions
    attributes:
      label: Attempted Solutions
      description: |
        If you've already tried to solve the problem within VRL's existing
        features and found a limitation that prevented you from succeeding, please
        describe it below in as much detail as possible.

        Ideally, this would include real code snippets that you tried and what results you got in each case.

        Please remove any sensitive information such as passwords before sharing code snippets and command lines.

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        If you have an idea for a way to address the problem via a change to
        VRL features, please describe it below.

        In this section, it's helpful to include specific examples of how what
        you are suggesting might look in VRL code, or on the command line,
        since that allows us to understand the full picture of what you are proposing.

        If you're not sure of some details, don't worry! When we evaluate the
        feature request we may suggest modifications as necessary to work within the
        design constraints of VRL.

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Are there any existing and related GitHub issues or Pull Requests that should be linked here?
