# Changelog
#
# Validates that a changelog entry was added.
# Runs on PRs when:
#   - opened/re-opened
#   - new commits pushed
#   - label is added or removed
# Runs on merge queues, but just passes, because it is a required check.

name: Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  # Due to merge queue requiring same status checks as PRs, must pass by default
  merge_group:
    types: [checks_requested]

jobs:
  validate-changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      PR_HAS_LABEL: ${{ contains( github.event.pull_request.labels.*.name, 'no-changelog') }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          if [[ $PR_HAS_LABEL == 'true' ]] ; then
            echo "'no-changelog' label detected."
            exit 0
          fi

          # helper script needs to reference the master branch to compare against
          git fetch origin main:refs/remotes/origin/main

          ./scripts/check_changelog_fragments.sh

  check-changelog:
    name: Changelog
    runs-on: ubuntu-latest
    needs: validate-changelog
    if: always()
    env:
      FAILED: ${{ contains(needs.*.result, 'failure') }}
    steps:
      - name: exit
        run: |
          echo "failed=${{ env.FAILED }}"
          if [[ "$FAILED" == "true" ]] ; then
            exit 1
          else
            exit 0
          fi
