name: Remove Awaiting Author Label

on:
  pull_request:
    types: [synchronize, review_requested]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "meta: awaiting author"
