name: Check Spelling

on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"

permissions:
  contents: read

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0
