name: Test Suite

on:
  pull_request:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - master

concurrency:
  # For pull requests, cancel running workflows, for master, run all
  #
  # `github.event.number` exists for pull requests, otherwise fall back to SHA
  # for master
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: full
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --workspace
      - name: Check code style
        run: cargo fmt --check --all
      - name: Run VRL tests
        run: |
          cd lib/tests
          cargo run
      - name: Clippy
        run: cargo clippy --workspace --all-targets
