name: Test Suite

concurrency:
  # For pull requests, cancel running workflows, for master, run all
  #
  # `github.event.number` exists for pull requests, otherwise fall back to SHA
  # for master
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: full
  RUST_TEST_THREADS: 1
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug

jobs:
  checks:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test -all
      - name: Check code style
        run: cargo fmt --check --all
      - name: Run VRL tests
        run: |
          cd lib/tests
          cargo run
