generate-desc:
	protoc --proto_path=. --include_imports --descriptor_set_out=test.desc test.proto
	protoc --proto_path=. --include_imports --descriptor_set_out=test_protobuf.desc test_protobuf.proto
	protoc --proto_path=. --include_imports --descriptor_set_out=test_protobuf3.desc test_protobuf3.proto
